former parseEmdContent changed <x></x> to <x/>
The first format causes:

org.scalatest.exceptions.TestFailedException: could not load test EMD
	...
	at nl.knaw.dans.easy.fedoratobag.fixture.EmdSupport.$anonfun$parseEmdContent$2(EmdSupport.scala:42)
	at nl.knaw.dans.lib.error.package$TryExtensions$.getOrRecover$extension(package.scala:163)
	at nl.knaw.dans.easy.fedoratobag.fixture.EmdSupport.parseEmdContent(EmdSupport.scala:42)
	at nl.knaw.dans.easy.fedoratobag.fixture.EmdSupport.parseEmdContent$(EmdSupport.scala:33)
	at nl.knaw.dans.easy.fedoratobag.DdmSpec.parseEmdContent(DdmSpec.scala:26)
	at nl.knaw.dans.easy.fedoratobag.DdmSpec.$anonfun$new$70(DdmSpec.scala:983)
            ...
Caused by: java.net.URISyntaxException: Illegal character in path at index 0: